name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        id: publish_pypi
        run: |
          pdm publish
          export ARCHIVE=$(ls dist | grep tar.gz)
          echo "archive=${ARCHIVE}" >> $GITHUB_OUTPUT

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./dist/${{ steps.publish_pypi.outputs.archive }}
          body_path: CHANGELOG.md
